In [66]:
import numpy as np 
class LinearAlgebra :
    def __init__ (self, narray):
      self.narray = narray
    def absoluteValue (self):
      absolute_ = np.fabs((self.narray))
      return (absolute_)
    def squareRoot (self):
      absolute_ = np.fabs((self.narray))
      squareroot_  = np.sqrt(absolute_)
      return squareroot_
    def squareValue (self):
      squared_ = np.square (self.narray)
      return squared_
    def exponentValue (self):
      exponented_ = np.exp(self.narray)
      return exponented_
    def logarifmValue (self, base=2.71):
      if base == 10 :
        logvalue_ = np.log10(self.narray)
      elif base == 2 :
        logvalue_ = np.log2(self.narray)
      elif base == 1 :
        logvalue_ = np.log1p(self.narray)
      elif base == 2.71 :
        logvalue_ = np.log(self.narray)
      else :
        logvalue_ = "Error:unidentified base"
      return logvalue_ 
    def signumValue (self):
      signvalue_ = np.sign(self.narray)
      return signvalue_
    def ceilumValue (self):
      ceilvalue_ = np.ceil(self.narray)
      return ceilvalue_
    def floorValue (self):
      floorvalue_=np.floor(self.narray)
      return floorvalue_
    def rintValue (self):
      rintvalue_=np.rint(self.narray)
      return rintvalue_
    def isnanValue (self):
      isnanvalue_=np.isnan(self.narray)
      return isnanvalue_
    def isfiniteValue (self):
      isfinitevalue_=np.isfinite(self.narray)
      return isfinitevalue_
    def isinfValue (self):
      isinfvalue_=np.isinf(self.narray)
      return isinfvalue_
    def trigonometricValue (self, function ="cos"):
      if function == "cos":
        trigonometricvalue_ = np.cos(self.narray)
      elif function == "cosh":
        trigonometricvalue_ = np.cosh(self.narray)
      elif function == "sin":
        trigonometricvalue_ = np.sin(self.narray)
      elif function == "sinh":
        trigonometricvalue_ = np.sinh(self.narray)
      elif function == "tg":
        trigonometricvalue_ = np.tg(self.narray)
      elif function == "tgh":
        trigonometricvalue_ = np.tgh(self.narray)
      else :
        trigonometricvalue_ = "Error:unidentified function"
      return trigonometricvalue_
    def inversetrigonometricValue (self, function ="arccos"):
      if function == "arccos":
        inversetrigonometricvalue_ = np.arccos(self.narray)
      elif function == "arccosh":
        inversetrigonometricvalue_ = np.arccosh(self.narray)
      elif function == "arcsin":
        inversetrigonometricvalue_ = np.arcsin(self.narray)
      elif function == "arcsinh":
        inversetrigonometricvalue_ = np.arcsinh(self.narray)
      elif function == "arctg":
        inversetrigonometricvalue_ = np.arctg(self.narray)
      elif function == "arctgh":
        inversetrigonometricvalue_ = np.arctgh(self.narray)
      else :
        inversetrigonometricvalue_ = "Error:unidentified function"
      return inversetrigonometricvalue_
    def logical_notValue (self):
      logical_notvalue = np.logical_not(self.narray)
      return logical_notvalue
    def makeSlice (self,somearray,start=0,end=1000,step=1):
      slice_ = slice(start,end,step)
      mask = np.ones_like(somearray, dtype=bool)
      mask[slice_] = False
      somearray[mask] = 0
      return somearray
    def arrayTransform (self,arraylike, n):
      transformed_ = np.repeat(arraylike[:, :, np.newaxis], n, axis=2)
      rez = []
      for i in range (n) :
        rez=transformed_[:, :, i]
        print (rez)
      return 0
def randomArray (somearray , rows ,colomns):

  return 0
if __name__ == "__main__":
 myarray = np.array(([10,2],[3,4],[5,6],[7,8]))
 executer = LinearAlgebra (myarray)
 myabs = executer.absoluteValue()
 mysqrt = executer.squareRoot()
 rez = executer.makeSlice(mysqrt, 1,5,1)
 logValue = executer.logarifmValue(2)
 rezult = executer.arrayTransform(myarray,3)
 arr2 = np.random.randn(4).reshape(2,2)
 print(arr2)
 arr2execute=LinearAlgebra(arr2)
 arr2abs = arr2execute.absoluteValue()
 print (arr2abs)
 arr3 = np.random.randn(9).reshape(3,3)
 print (arr3)
 arr3execute = LinearAlgebra(arr3)
 arr3log = arr3execute.logarifmValue()
 print(arr3log)
 arr4 = np.random.randn(16).reshape(4,4)
 print (arr4)
 arr4executer = LinearAlgebra(arr4)
 arr4transform = arr4executer.arrayTransform(arr4,3)

[[10  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]]
[[10  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]]
[[10  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]]
[[-0.33146768  1.15938224]
 [ 1.12837744 -0.48398694]]
[[0.33146768 1.15938224]
 [1.12837744 0.48398694]]
[[ 1.53295049  0.222642    0.80184379]
 [-1.84248026  1.01150111 -0.18916766]
 [-0.14957941 -0.47456106  0.96131738]]
[[ 0.4271943  -1.50219016 -0.22084147]
 [        nan  0.01143548         nan]
 [        nan         nan -0.03945066]]
[[-1.49240111  0.6100348  -1.68843555  0.26490133]
 [-0.82356492 -0.74418997  0.0106724   1.32480745]
 [ 1.39876236  0.40750742  0.35415843 -0.42563767]
 [ 0.48154542  1.35458638  0.37177369 -0.41913011]]
[[-1.49240111  0.6100348  -1.68843555  0.26490133]
 [-0.82356492 -0.74418997  0.0106724   1.32480745]
 [ 1.39876236  0.40750742  0.35415843 -0.42563767]
 [ 0.48154542  1.35458638  0.37177369 -0.41913011]]
[[-1.49240111  0.6100348  -1.68843555  0.26490133]
 [-0.82356492 -0.74418997  0.0106724   1.32480745]
 [ 1.39876236  0.40750742  0.354158

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:26: RuntimeWarning: invalid value encountered in log
